final supportLanguages = {
  'Arabic': 'ar',
  'Afrikaans': 'af',
  'Bangla': 'bn',
  'Burmese': 'my',
  'Chinese (Simplified)': 'zh-Hans',
  'Chinese (Traditional)': 'zh-Hant',
  'Chinese': 'zh-CN',
  'Dutch': 'nl',
  'English': 'en',
  'French': 'fr',
  'Finnish': 'fi',
  'Greek': 'el',
  'Hindi': 'hi',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  'Malay': 'ml',
  'Malayalam': 'ml',
  'Portugese': 'pt',
  'Russian': 'ru',
  'Spanish': 'es',
  'Tamil': 'ta',
  'Telegu': 'te',
  'Thai': 'th',
  'Turkish': 'tr',
  'Urdu': 'ur',
  'Vietnamese': 'vi',
  'ALL AVAILABLE': 'all',
};
